/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/ui/button/BaseButton.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppInput: typeof import('./components/ui/input/BaseInput.vue')['default']
    AppLayout: typeof import('./layouts/AppLayout.vue')['default']
    AppSideBar: typeof import('./components/layout/AppSideBar.vue')['default']
    Badge: typeof import('./components/ui/badge/Badge.vue')['default']
    BaseButton: typeof import('./components/ui/button/BaseButton.vue')['default']
    BaseInput: typeof import('./components/ui/input/BaseInput.vue')['default']
    Button: typeof import(./components/ui/input/AppInput.vuevue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    Menubar: typeof import('./components/ui/menubar/Menubar.vue')['default']
    MenubarCheckboxItem: typeof import('./components/ui/menubar/MenubarCheckboxItem.vue')['default']
    MenubarContent: typeof import('./components/ui/menubar/MenubarContent.vue')['default']
    MenubarGroup: typeof import('./components/ui/menubar/MenubarGroup.vue')['default']
    MenubarItem: typeof import('./components/ui/menubar/MenubarItem.vue')['default']
    MenubarLabel: typeof import('./components/ui/menubar/MenubarLabel.vue')['default']
    MenubarMenu: typeof import('./components/ui/menubar/MenubarMenu.vue')['default']
    MenubarRadioGroup: typeof import('./components/ui/menubar/MenubarRadioGroup.vue')['default']
    MenubarRadioItem: typeof import('./components/ui/menubar/MenubarRadioItem.vue')['default']
    MenubarSeparator: typeof import('./components/ui/menubar/MenubarSeparator.vue')['default']
    MenubarShortcut: typeof import('./components/ui/menubar/MenubarShortcut.vue')['default']
    MenubarSub: typeof import('./components/ui/menubar/MenubarSub.vue')['default']
    MenubarSubContent: typeof import('./components/ui/menubar/MenubarSubContent.vue')['default']
    MenubarSubTrigger: typeof import('./components/ui/menubar/MenubarSubTrigger.vue')['default']
    MenubarTrigger: typeof import('./components/ui/menubar/MenubarTrigger.vue')['default']
    MenuItems: typeof import('./components/ui/MenuItems.vue')['default']
    NavigationButton: typeof import('./components/ui/NavigationButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/ui/SearchInput.vue')['default']
  }
}
