/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBadge: typeof import('./components/ui/badge/AppBadge.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./layouts/AppLayout.vue')['default']
    AppSideBar: typeof import('./components/layout/AppSideBar.vue')['default']
    BaseButton: typeof import('./components/ui/button/BaseButton.vue')['default']
    BaseInput: typeof import('./components/ui/input/BaseInput.vue')['default']
    Menubar: typeof import('./components/ui/menubar/Menubar.vue')['default']
    MenubarCheckboxItem: typeof import('./components/ui/menubar/MenubarCheckboxItem.vue')['default']
    MenubarContent: typeof import('./components/ui/menubar/MenubarContent.vue')['default']
    MenubarGroup: typeof import('./components/ui/menubar/MenubarGroup.vue')['default']
    MenubarItem: typeof import('./components/ui/menubar/MenubarItem.vue')['default']
    MenubarLabel: typeof import('./components/ui/menubar/MenubarLabel.vue')['default']
    MenubarMenu: typeof import('./components/ui/menubar/MenubarMenu.vue')['default']
    MenubarRadioGroup: typeof import('./components/ui/menubar/MenubarRadioGroup.vue')['default']
    MenubarRadioItem: typeof import('./components/ui/menubar/MenubarRadioItem.vue')['default']
    MenubarSeparator: typeof import('./components/ui/menubar/MenubarSeparator.vue')['default']
    MenubarShortcut: typeof import('./components/ui/menubar/MenubarShortcut.vue')['default']
    MenubarSub: typeof import('./components/ui/menubar/MenubarSub.vue')['default']
    MenubarSubContent: typeof import('./components/ui/menubar/MenubarSubContent.vue')['default']
    MenubarSubTrigger: typeof import('./components/ui/menubar/MenubarSubTrigger.vue')['default']
    MenubarTrigger: typeof import('./components/ui/menubar/MenubarTrigger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sheet: typeof import('./components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./components/ui/sheet/SheetHeader.vue')['default']
    SheetOverlay: typeof import('./components/ui/sheet/SheetOverlay.vue')['default']
    SheetTitle: typeof import('./components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./components/ui/sheet/SheetTrigger.vue')['default']
  }
}
